language: php

php:
  - '7.1'
  - '7.2'

install: composer install

script:
  - mkdir build/logs -p
  - phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
  - bash <(curl -s https://codecov.io/bash)
  - php vendor/bin/codacycoverage clover build/logs/clover.xml